name: ME2VibrationsAppBeta #Env name

dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy==1.19.5
      - dash
      - dash-renderer
      - dash-core-components
      - dash-html-components
      - dash-bootstrap-components
      - plotly
      - pandas==1.1.5   # Something up with Heroku when you use latest version!! So use 1.1.5
      - gunicorn # for app deployment